// Deterministic HTML -> PDF rendering via headless Chromium (Playwright).
//
// The PDF is rendered by the same engine everywhere, so the artifact does not
// depend on the user's browser. Current-shell pages are WYSIWYG by
// construction — the .page element is the sheet, printed 1:1 into a
// zero-margin page box — so nothing needs to run before printing. Pages
// generated by older shells still carry a computePrintFit() zoom pipeline;
// invoking it (when defined) keeps their PDFs rendering as they always did.
import { chromium } from "playwright";

let browserPromise = null;

function launchOptions() {
  const opts = { headless: true };
  // Explicit executable override for environments with a system-managed
  // Chromium (CI sandboxes, nix, etc.). Playwright's own browser cache
  // (PLAYWRIGHT_BROWSERS_PATH) is honored automatically without this.
  if (process.env.PRINT_SKILL_CHROMIUM) {
    opts.executablePath = process.env.PRINT_SKILL_CHROMIUM;
  }
  return opts;
}

async function getBrowser() {
  if (!browserPromise) {
    browserPromise = chromium.launch(launchOptions()).then((browser) => {
      browser.on("disconnected", () => {
        browserPromise = null;
      });
      return browser;
    });
    browserPromise.catch(() => {
      browserPromise = null;
    });
  }
  return browserPromise;
}

/**
 * Render the page at `url` to a PDF buffer.
 * The page is expected to be a print-skill page (shell present), but any HTML
 * renders — the legacy computePrintFit hook is invoked only when the page
 * defines it (old-shell pages).
 */
export async function renderPdf(url) {
  const browser = await getBrowser();
  const context = await browser.newContext({
    viewport: { width: 1440, height: 1080 },
  });
  try {
    const page = await context.newPage();
    // networkidle so web fonts are loaded before printing — fallback-font
    // metrics wrap lines differently than the fonts the screen view shows.
    await page.goto(url, { waitUntil: "networkidle", timeout: 30_000 });
    await page.evaluate(() => {
      if (typeof computePrintFit === "function") computePrintFit();
    });
    // preferCSSPageSize: the page's @page rule (letter / A4 / legal /
    // landscape / 5.5in 8.5in) decides the sheet; Letter is only the
    // fallback for pages that declare nothing.
    return await page.pdf({
      format: "Letter",
      preferCSSPageSize: true,
      printBackground: true,
    });
  } finally {
    await context.close();
  }
}

export async function closeBrowser() {
  if (browserPromise) {
    const browser = await browserPromise.catch(() => null);
    browserPromise = null;
    if (browser) await browser.close();
  }
}
